/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.lab_6_xo_file;

import java.io.*;
import java.util.*;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author 65160230 Piyapong
 */
public class Lab_6_XO_GUI_JFrame extends javax.swing.JFrame {

    private XOPlayer O;
    private XOPlayer X;
    private XOBoard board;
    private int row;
    private int col;

    /**
     * Creates new form Lab_5_XO_GUI_JFrame
     */
    public Lab_6_XO_GUI_JFrame() {
        initComponents();
        //config player to variable
        O = new XOPlayer('O');
        X = new XOPlayer('X');
        load();

    }

    private void writePlayer() {
        FileOutputStream fos = null;
        try {
            File file = new File("friends.dat");
            fos = new FileOutputStream(file);
            ObjectOutputStream oos = new ObjectOutputStream(fos);
            oos.writeObject(X);
            oos.writeObject(O);
            oos.close();
        } catch (FileNotFoundException ex) {
            System.out.println("File Not Found.");
        } catch (IOException ex) {
            System.out.println("I/O error.");
        } finally {
            try {
                fos.close();
            } catch (IOException ex) {
                System.out.println("I/O error.");
            }
        }
    }

    private void readPlayer() {
        FileInputStream fis = null;
        try {
            File file = new File("friends.dat");
            fis = new FileInputStream(file);
            ObjectInputStream ois = new ObjectInputStream(fis);
            X = (XOPlayer) ois.readObject();
            O = (XOPlayer) ois.readObject();
            ois.close();
        } catch (FileNotFoundException ex) {
            System.out.println("File Not Found.");
        } catch (IOException ex) {
            System.out.println("I/O error.");
        } catch (ClassNotFoundException ex) {
            System.out.println("Class Not Found.");
        } finally {
            try {
                fis.close();
            } catch (IOException ex) {
                System.out.println("I/O error.");
            }
        }
    }

    public void showTable() {
        char[][] table = board.getTable();
        btnPlayer1.setText(String.valueOf(table[0][0]));
        btnPlayer2.setText(String.valueOf(table[0][1]));
        btnPlayer3.setText(String.valueOf(table[0][2]));
        btnPlayer4.setText(String.valueOf(table[1][0]));
        btnPlayer5.setText(String.valueOf(table[1][1]));
        btnPlayer6.setText(String.valueOf(table[1][2]));
        btnPlayer7.setText(String.valueOf(table[2][0]));
        btnPlayer8.setText(String.valueOf(table[2][1]));
        btnPlayer9.setText(String.valueOf(table[2][2]));
    }

    public void showTurn() {
        XOPlayer currentPlayer = board.getCurrentPlayer();
        lblStatus.setText("  Turn : " + currentPlayer.getSymbol());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelOfButton = new javax.swing.JPanel();
        btnPlayer1 = new javax.swing.JButton();
        btnPlayer2 = new javax.swing.JButton();
        btnPlayer3 = new javax.swing.JButton();
        btnPlayer4 = new javax.swing.JButton();
        btnPlayer5 = new javax.swing.JButton();
        btnPlayer6 = new javax.swing.JButton();
        btnPlayer7 = new javax.swing.JButton();
        btnPlayer8 = new javax.swing.JButton();
        btnPlayer9 = new javax.swing.JButton();
        jPanelOfText = new javax.swing.JPanel();
        lblPlayerX = new javax.swing.JPanel();
        lblXPlayer = new javax.swing.JLabel();
        lblXWin = new javax.swing.JLabel();
        lblXLose = new javax.swing.JLabel();
        lblXDraw = new javax.swing.JLabel();
        lblPlayerO = new javax.swing.JPanel();
        lblOPlayer = new javax.swing.JLabel();
        lblOWin = new javax.swing.JLabel();
        lblOLose = new javax.swing.JLabel();
        lblODraw = new javax.swing.JLabel();
        jPanelOfGame = new javax.swing.JPanel();
        lblStatus = new javax.swing.JLabel();
        btnNewGame = new javax.swing.JButton();
        btnClose = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("XO Game");
        setBackground(new java.awt.Color(105, 79, 142));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jPanelOfButton.setBackground(new java.awt.Color(182, 146, 194));
        jPanelOfButton.setPreferredSize(new java.awt.Dimension(350, 350));

        btnPlayer1.setBackground(new java.awt.Color(254, 250, 224));
        btnPlayer1.setFont(new java.awt.Font("Sarabun", 1, 36)); // NOI18N
        btnPlayer1.setForeground(new java.awt.Color(105, 79, 142));
        btnPlayer1.setText("-");
        btnPlayer1.setOpaque(false);
        btnPlayer1.setPreferredSize(new java.awt.Dimension(105, 105));
        btnPlayer1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPlayer1ActionPerformed(evt);
            }
        });

        btnPlayer2.setBackground(new java.awt.Color(254, 250, 224));
        btnPlayer2.setFont(new java.awt.Font("Sarabun", 1, 36)); // NOI18N
        btnPlayer2.setForeground(new java.awt.Color(105, 79, 142));
        btnPlayer2.setText("-");
        btnPlayer2.setOpaque(false);
        btnPlayer2.setPreferredSize(new java.awt.Dimension(105, 105));
        btnPlayer2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPlayer2ActionPerformed(evt);
            }
        });

        btnPlayer3.setBackground(new java.awt.Color(254, 250, 224));
        btnPlayer3.setFont(new java.awt.Font("Sarabun", 1, 36)); // NOI18N
        btnPlayer3.setForeground(new java.awt.Color(105, 79, 142));
        btnPlayer3.setText("-");
        btnPlayer3.setOpaque(false);
        btnPlayer3.setPreferredSize(new java.awt.Dimension(105, 105));
        btnPlayer3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPlayer3ActionPerformed(evt);
            }
        });

        btnPlayer4.setBackground(new java.awt.Color(254, 250, 224));
        btnPlayer4.setFont(new java.awt.Font("Sarabun", 1, 36)); // NOI18N
        btnPlayer4.setForeground(new java.awt.Color(105, 79, 142));
        btnPlayer4.setText("-");
        btnPlayer4.setOpaque(false);
        btnPlayer4.setPreferredSize(new java.awt.Dimension(105, 105));
        btnPlayer4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPlayer4ActionPerformed(evt);
            }
        });

        btnPlayer5.setBackground(new java.awt.Color(254, 250, 224));
        btnPlayer5.setFont(new java.awt.Font("Sarabun", 1, 36)); // NOI18N
        btnPlayer5.setForeground(new java.awt.Color(105, 79, 142));
        btnPlayer5.setText("-");
        btnPlayer5.setOpaque(false);
        btnPlayer5.setPreferredSize(new java.awt.Dimension(105, 105));
        btnPlayer5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPlayer5ActionPerformed(evt);
            }
        });

        btnPlayer6.setBackground(new java.awt.Color(254, 250, 224));
        btnPlayer6.setFont(new java.awt.Font("Sarabun", 1, 36)); // NOI18N
        btnPlayer6.setForeground(new java.awt.Color(105, 79, 142));
        btnPlayer6.setText("-");
        btnPlayer6.setOpaque(false);
        btnPlayer6.setPreferredSize(new java.awt.Dimension(105, 105));
        btnPlayer6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPlayer6ActionPerformed(evt);
            }
        });

        btnPlayer7.setBackground(new java.awt.Color(254, 250, 224));
        btnPlayer7.setFont(new java.awt.Font("Sarabun", 1, 36)); // NOI18N
        btnPlayer7.setForeground(new java.awt.Color(105, 79, 142));
        btnPlayer7.setText("-");
        btnPlayer7.setOpaque(false);
        btnPlayer7.setPreferredSize(new java.awt.Dimension(105, 105));
        btnPlayer7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPlayer7ActionPerformed(evt);
            }
        });

        btnPlayer8.setBackground(new java.awt.Color(254, 250, 224));
        btnPlayer8.setFont(new java.awt.Font("Sarabun", 1, 36)); // NOI18N
        btnPlayer8.setForeground(new java.awt.Color(105, 79, 142));
        btnPlayer8.setText("-");
        btnPlayer8.setOpaque(false);
        btnPlayer8.setPreferredSize(new java.awt.Dimension(105, 105));
        btnPlayer8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPlayer8ActionPerformed(evt);
            }
        });

        btnPlayer9.setBackground(new java.awt.Color(254, 250, 224));
        btnPlayer9.setFont(new java.awt.Font("Sarabun", 1, 36)); // NOI18N
        btnPlayer9.setForeground(new java.awt.Color(105, 79, 142));
        btnPlayer9.setText("-");
        btnPlayer9.setOpaque(false);
        btnPlayer9.setPreferredSize(new java.awt.Dimension(105, 105));
        btnPlayer9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPlayer9ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelOfButtonLayout = new javax.swing.GroupLayout(jPanelOfButton);
        jPanelOfButton.setLayout(jPanelOfButtonLayout);
        jPanelOfButtonLayout.setHorizontalGroup(
            jPanelOfButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelOfButtonLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelOfButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnPlayer1, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnPlayer4, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnPlayer7, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelOfButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnPlayer2, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnPlayer5, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnPlayer8, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelOfButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnPlayer9, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnPlayer3, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnPlayer6, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelOfButtonLayout.setVerticalGroup(
            jPanelOfButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelOfButtonLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanelOfButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelOfButtonLayout.createSequentialGroup()
                        .addComponent(btnPlayer3, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnPlayer6, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnPlayer9, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelOfButtonLayout.createSequentialGroup()
                        .addComponent(btnPlayer2, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnPlayer5, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnPlayer8, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelOfButtonLayout.createSequentialGroup()
                        .addComponent(btnPlayer1, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnPlayer4, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnPlayer7, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(21, 21, 21))
        );

        jPanelOfText.setBackground(new java.awt.Color(182, 146, 194));
        jPanelOfText.setPreferredSize(new java.awt.Dimension(350, 350));

        lblPlayerX.setBackground(new java.awt.Color(254, 250, 224));
        lblPlayerX.setPreferredSize(new java.awt.Dimension(80, 175));

        lblXPlayer.setFont(new java.awt.Font("Sarabun", 1, 24)); // NOI18N
        lblXPlayer.setForeground(new java.awt.Color(105, 79, 142));
        lblXPlayer.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblXPlayer.setText("X Player");

        lblXWin.setFont(new java.awt.Font("Sarabun", 0, 18)); // NOI18N
        lblXWin.setForeground(new java.awt.Color(105, 79, 142));
        lblXWin.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblXWin.setText("Win : 0");

        lblXLose.setFont(new java.awt.Font("Sarabun", 0, 18)); // NOI18N
        lblXLose.setForeground(new java.awt.Color(105, 79, 142));
        lblXLose.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblXLose.setText("Lose : 0");

        lblXDraw.setFont(new java.awt.Font("Sarabun", 0, 18)); // NOI18N
        lblXDraw.setForeground(new java.awt.Color(105, 79, 142));
        lblXDraw.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblXDraw.setText("Draw : 0");

        javax.swing.GroupLayout lblPlayerXLayout = new javax.swing.GroupLayout(lblPlayerX);
        lblPlayerX.setLayout(lblPlayerXLayout);
        lblPlayerXLayout.setHorizontalGroup(
            lblPlayerXLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblXPlayer, javax.swing.GroupLayout.DEFAULT_SIZE, 332, Short.MAX_VALUE)
            .addComponent(lblXWin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(lblXLose, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(lblXDraw, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        lblPlayerXLayout.setVerticalGroup(
            lblPlayerXLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(lblPlayerXLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblXPlayer)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblXWin)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblXLose)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblXDraw)
                .addContainerGap(22, Short.MAX_VALUE))
        );

        lblPlayerO.setBackground(new java.awt.Color(254, 250, 224));
        lblPlayerO.setPreferredSize(new java.awt.Dimension(80, 175));

        lblOPlayer.setFont(new java.awt.Font("Sarabun", 1, 24)); // NOI18N
        lblOPlayer.setForeground(new java.awt.Color(105, 79, 142));
        lblOPlayer.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblOPlayer.setText("O Player");

        lblOWin.setFont(new java.awt.Font("Sarabun", 0, 18)); // NOI18N
        lblOWin.setForeground(new java.awt.Color(105, 79, 142));
        lblOWin.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblOWin.setText("Win : 0");

        lblOLose.setFont(new java.awt.Font("Sarabun", 0, 18)); // NOI18N
        lblOLose.setForeground(new java.awt.Color(105, 79, 142));
        lblOLose.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblOLose.setText("Lose : 0");

        lblODraw.setFont(new java.awt.Font("Sarabun", 0, 18)); // NOI18N
        lblODraw.setForeground(new java.awt.Color(105, 79, 142));
        lblODraw.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblODraw.setText("Draw : 0");

        javax.swing.GroupLayout lblPlayerOLayout = new javax.swing.GroupLayout(lblPlayerO);
        lblPlayerO.setLayout(lblPlayerOLayout);
        lblPlayerOLayout.setHorizontalGroup(
            lblPlayerOLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(lblPlayerOLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(lblPlayerOLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblOPlayer, javax.swing.GroupLayout.DEFAULT_SIZE, 308, Short.MAX_VALUE)
                    .addComponent(lblOWin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblOLose, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblODraw, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        lblPlayerOLayout.setVerticalGroup(
            lblPlayerOLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(lblPlayerOLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblOPlayer)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblOWin)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblOLose)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblODraw)
                .addContainerGap(22, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanelOfTextLayout = new javax.swing.GroupLayout(jPanelOfText);
        jPanelOfText.setLayout(jPanelOfTextLayout);
        jPanelOfTextLayout.setHorizontalGroup(
            jPanelOfTextLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelOfTextLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelOfTextLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblPlayerX, javax.swing.GroupLayout.DEFAULT_SIZE, 332, Short.MAX_VALUE)
                    .addComponent(lblPlayerO, javax.swing.GroupLayout.DEFAULT_SIZE, 332, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanelOfTextLayout.setVerticalGroup(
            jPanelOfTextLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelOfTextLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(lblPlayerX, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblPlayerO, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanelOfGame.setBackground(new java.awt.Color(182, 146, 194));

        lblStatus.setBackground(new java.awt.Color(254, 250, 224));
        lblStatus.setFont(new java.awt.Font("Sarabun", 1, 24)); // NOI18N
        lblStatus.setForeground(new java.awt.Color(105, 79, 142));
        lblStatus.setText("  Welcome to XO Game");
        lblStatus.setToolTipText("");
        lblStatus.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        lblStatus.setOpaque(true);

        btnNewGame.setBackground(new java.awt.Color(254, 250, 224));
        btnNewGame.setFont(new java.awt.Font("Sarabun", 1, 18)); // NOI18N
        btnNewGame.setForeground(new java.awt.Color(105, 79, 142));
        btnNewGame.setText("New Game");
        btnNewGame.setOpaque(false);
        btnNewGame.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNewGameActionPerformed(evt);
            }
        });

        btnClose.setBackground(new java.awt.Color(254, 250, 224));
        btnClose.setFont(new java.awt.Font("Sarabun", 1, 18)); // NOI18N
        btnClose.setForeground(new java.awt.Color(105, 79, 142));
        btnClose.setText("Close");
        btnClose.setOpaque(false);
        btnClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCloseActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelOfGameLayout = new javax.swing.GroupLayout(jPanelOfGame);
        jPanelOfGame.setLayout(jPanelOfGameLayout);
        jPanelOfGameLayout.setHorizontalGroup(
            jPanelOfGameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelOfGameLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 379, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnNewGame, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnClose, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelOfGameLayout.setVerticalGroup(
            jPanelOfGameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelOfGameLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelOfGameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnClose, javax.swing.GroupLayout.DEFAULT_SIZE, 71, Short.MAX_VALUE)
                    .addComponent(lblStatus, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnNewGame, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanelOfGame, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanelOfButton, javax.swing.GroupLayout.PREFERRED_SIZE, 393, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanelOfText, javax.swing.GroupLayout.DEFAULT_SIZE, 356, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanelOfText, javax.swing.GroupLayout.DEFAULT_SIZE, 399, Short.MAX_VALUE)
                    .addComponent(jPanelOfButton, javax.swing.GroupLayout.DEFAULT_SIZE, 399, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanelOfGame, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void gameProcess() {
        board.setRowCol(row, col);
        showTable();
        if (board.isFinish()) {
            doFinish();
            return;
        }
        board.switchTurn();
        showTurn();
    }

    private void doFinish() {
        if (board.checkDraw()) {
            lblStatus.setText("  It's a Draw.");
        } else if (board.checkWin()) {
            lblStatus.setText("  Congratulations, " + board.getCurrentPlayer().getSymbol() + " is winner.");
        }
        setEnableBoard(false);
        board.updateStats();
        showPlayerInfo();
        btnNewGame.setEnabled(true);
    }

    private void setEnableBoard(boolean isEnable) {
        btnPlayer1.setEnabled(isEnable);
        btnPlayer2.setEnabled(isEnable);
        btnPlayer3.setEnabled(isEnable);
        btnPlayer4.setEnabled(isEnable);
        btnPlayer5.setEnabled(isEnable);
        btnPlayer6.setEnabled(isEnable);
        btnPlayer7.setEnabled(isEnable);
        btnPlayer8.setEnabled(isEnable);
        btnPlayer9.setEnabled(isEnable);
    }

    private void btnPlayer1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPlayer1ActionPerformed
        row = 0;
        col = 0;
        gameProcess();
    }//GEN-LAST:event_btnPlayer1ActionPerformed

    private void btnPlayer2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPlayer2ActionPerformed
        row = 0;
        col = 1;
        gameProcess();
    }//GEN-LAST:event_btnPlayer2ActionPerformed

    private void btnPlayer3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPlayer3ActionPerformed
        row = 0;
        col = 2;
        gameProcess();
    }//GEN-LAST:event_btnPlayer3ActionPerformed

    private void btnPlayer4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPlayer4ActionPerformed
        row = 1;
        col = 0;
        gameProcess();
    }//GEN-LAST:event_btnPlayer4ActionPerformed

    private void btnPlayer5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPlayer5ActionPerformed
        row = 1;
        col = 1;
        gameProcess();
    }//GEN-LAST:event_btnPlayer5ActionPerformed

    private void btnPlayer6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPlayer6ActionPerformed
        row = 1;
        col = 2;
        gameProcess();
    }//GEN-LAST:event_btnPlayer6ActionPerformed

    private void btnPlayer7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPlayer7ActionPerformed
        row = 2;
        col = 0;
        gameProcess();
    }//GEN-LAST:event_btnPlayer7ActionPerformed

    private void btnPlayer8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPlayer8ActionPerformed
        row = 2;
        col = 1;
        gameProcess();
    }//GEN-LAST:event_btnPlayer8ActionPerformed

    private void btnPlayer9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPlayer9ActionPerformed
        row = 2;
        col = 2;
        gameProcess();
    }//GEN-LAST:event_btnPlayer9ActionPerformed

    private void btnNewGameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNewGameActionPerformed
        setEnableBoard(true);
        btnNewGame.setEnabled(false);
        load();
    }//GEN-LAST:event_btnNewGameActionPerformed

    private void btnCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCloseActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnCloseActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Lab_6_XO_GUI_JFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Lab_6_XO_GUI_JFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Lab_6_XO_GUI_JFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Lab_6_XO_GUI_JFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Lab_6_XO_GUI_JFrame().setVisible(true);
            }
        });
    }

    private void load() {
        board = new XOBoard(X, O);
        btnNewGame.setEnabled(false);
        showTable();
        showPlayerInfo();
        showTurn();
    }

    private void showPlayerInfo() {
        lblXWin.setText("Win : " + X.getWinTimes());
        lblXLose.setText("Lose : " + X.getLoseTimes());
        lblXDraw.setText("Draw : " + X.getDrawTimes());
        lblOWin.setText("Win : " + O.getWinTimes());
        lblOLose.setText("Lose : " + O.getLoseTimes());
        lblODraw.setText("Draw : " + O.getDrawTimes());

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnClose;
    private javax.swing.JButton btnNewGame;
    private javax.swing.JButton btnPlayer1;
    private javax.swing.JButton btnPlayer2;
    private javax.swing.JButton btnPlayer3;
    private javax.swing.JButton btnPlayer4;
    private javax.swing.JButton btnPlayer5;
    private javax.swing.JButton btnPlayer6;
    private javax.swing.JButton btnPlayer7;
    private javax.swing.JButton btnPlayer8;
    private javax.swing.JButton btnPlayer9;
    private javax.swing.JPanel jPanelOfButton;
    private javax.swing.JPanel jPanelOfGame;
    private javax.swing.JPanel jPanelOfText;
    private javax.swing.JLabel lblODraw;
    private javax.swing.JLabel lblOLose;
    private javax.swing.JLabel lblOPlayer;
    private javax.swing.JLabel lblOWin;
    private javax.swing.JPanel lblPlayerO;
    private javax.swing.JPanel lblPlayerX;
    private javax.swing.JLabel lblStatus;
    private javax.swing.JLabel lblXDraw;
    private javax.swing.JLabel lblXLose;
    private javax.swing.JLabel lblXPlayer;
    private javax.swing.JLabel lblXWin;
    // End of variables declaration//GEN-END:variables

}
